### ISSUE TITLE
Events 拼写错误

### ISSUE THREAD

**Issue by chaozhangdev** [hejialianghe/Senior-FrontEnd#24]
https://hejialianghe.gitee.io/vue/vueBase.html#_2-5-1-%E7%BB%84%E4%BB%B6%E6%B3%A8%E5%86%8C

![image](https://user-images.githubusercontent.com/43924959/125031498-9ad3cd00-e041-11eb-8c64-2b87ec33d2d7.png)

**Comment by hejialianghe** [comment]
以修改
