### ISSUE TITLE
2.6.1 memozition（缓存函数）的缓存判断语句好像可以调整下

### ISSUE THREAD

**Issue by 827753181** [hejialianghe/Senior-FrontEnd#40]
![image](https://user-images.githubusercontent.com/33085548/136174390-b6a6df8a-928a-42ab-b905-5064f9e7db93.png)
使用 !cache[address] 或者 !cache[key] 做判断会把0也判断进去，这也是
🍅 案例：求斐波那且数列
memoize后的fibonacci会执行12次的原因

**Comment by mty-qw** [comment]
![image](https://user-images.githubusercontent.com/45986485/153556057-db946212-7a9b-4db7-8293-99dcc002f323.png)

这个缓存函数每次都会执行，判断条件是有问题的

**Comment by lxx1997** [comment]
![image](https://user-images.githubusercontent.com/50178596/218687396-3d0b9e5a-b321-4dbe-beb9-0021ffbe7e62.png)
如果cache[key] 获取到为 0 或者 空字符串或者 false 还是会重新计算，我觉得可以判断 一下cache[类型] 是否为 undefined 类型

**Comment by hejialianghe** [comment]
已改
