### ISSUE TITLE
2.1.1 函数变量有点问题

### ISSUE THREAD

**Issue by Indomite** [hejialianghe/Senior-FrontEnd#43]
`function fn() {
  var t = 10
  var f = 10
  console.log(i + j)
}
// 我们直接打印fn会出现一段字符串
console.log(fn)
/*
 打印结果
  f fn() {
     var t=10;
     var f=10;
     console.log(i+j)
 }
*/

// 加上括号才执行里面的代码
fn() // 20`

这里应该是 i j 吧

**Comment by hejialianghe** [comment]
我改一下，谢谢指正
